name: Deploy GO application

on:
  push:
    branches:
      - deploy_to_server

jobs: 
  deploy:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Setup go env
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.1
      
      